# Generated by Django 2.1.3 on 2018-11-24 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strain',
            name='cbd',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='strain',
            name='thc',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
