# Generated by Django 2.1.3 on 2019-04-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20190113_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='advanced',
            name='stats',
            field=models.BooleanField(default=0),
        ),
    ]
